name: Olatano
title: Olatano
description: >-
  Je vais vous transformer dans un monde merveilleux d'exploration de l'histoire des Ngwè-Myènè. Voyage, Culture, Style de vie.
 Ôkani !
logo: assets/images/logo.png
favicon: assets/images/logo.png
baseurl: ''
google_analytics: 
disqus: demowebsite
mailchimp-list: >-
  
include:
  - _pages
permalink: '/:title/'
email: yoenagondjo@gmail.com
authors:
  sal:
    name: AGONDJO
    display_name: AGONDJO
    gravatar: 
    email: yoenagondjo@gmail.com
    web: 'https://yoenagondjo.landen.co'
    twitter: ''
    description: >-
      Fondateur d'Olatano, Designer Web Marketing Digital, Amoureux du Numérique et du Leadership féminin.
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
paginate: 6
paginate_path: '/page:num/'
highlighter: none
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
adsense: disabled
adsense-data-ad-client: 
adsense-data-ad-slot: ''
lazyimages: disabled
authorbox: disabled
sass:
  sass_dir: _sass
  style: compressed
exclude:
  - changelog.md
  - LICENSE.txt
  - README.md
  - Gemfile
  - Gemfile.lock
url: ''
